# Generated by Django 5.0.3 on 2024-03-20 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_contact_owner'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cadegory',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='cadegory',
            new_name='category',
        ),
    ]
